bf: doi2bib

diff --git a/mysh/doi2bib b/mysh/doi2bib
--- a/mysh/doi2bib
+++ b/mysh/doi2bib
@@ -5,6 +5,7 @@ normal=$(tput sgr0)
 me=$(basename "$0")
 doi=""
 b=""
+q=""
 while test $# -gt 0; do
   case "$1" in
     -h|--help)
@@ -16,6 +17,10 @@ while test $# -gt 0; do
       echo "-h, --help                show brief help"
       echo "-x XXX[,YYY]              remove unneeded items according to specified key(s)"
       exit 0
+      ;;
+    -q)
+      shift
+      q="q"
       ;;
     -x)
       shift
@@ -33,8 +38,19 @@ while test $# -gt 0; do
   esac
 done
 
+if test -z "$b" ; then
+  b="month"
+else
+  b="${b},month"
+fi
+
 if test -z "$doi" ; then
-  echo "DOI is mandaroty but not specified!"
+  if test -z "$q" ; then echo "DOI is mandaroty but not specified!" ; fi
+  exit 1
+fi
+
+if [[ "$doi" != "10."* ]] ; then
+  if test -z "$q" ; then echo "Not a valid DOI specified!" ; fi
   exit 1
 fi
 
@@ -67,15 +83,71 @@ function _pure_t1 {
   fi
 }
 
-doi=$(echo "$doi" | sed 's/https\?:\/\/doi.org\///')
-o=$(curl -sLH "Accept: application/x-bibtex" https://doi.org/"$doi")
-tt=$(_t1 "${o}")
-tt=$(_pure_t1 "$tt")
-o=$(echo $o | sed -E 's/(\w*)_[0-9]*([0-9]{2}),/\L\1\2'"${tt}"',/' | sed 's/month=\w*,\? \?//g' | sed 's/DOI=/doi=/' | sed 's/\(pages\s\?=\s\?{\s\?[0-9]\+\s\?\)[–-]\(\s\?[0-9]\+\)/\1--\2/')
-if test -n "$b"; then
+function _rm_items {
+  _o="$1"
   for i in $(echo "$b" | tr "," " "); do
-    o=$(echo "$o" | sed 's/'"$i"'={[^\{\}]*},\? \?//gI')
+    _o=$(echo "$_o" | sed 's/'"$i"'={[^\{\}]*},\? \?//gI')
   done
+  echo "$_o"
+}
+
+function _tolines {
+  _o="$1"
+  echo "$_o" | sed 's/\s*\(\w\+\)=\({[^\{\}]*}\)/\n  \L\1\E = \2/g' | sed 's/},\? \?}/}\n}\n/'
+}
+
+function _keys {
+  o0="$1"
+  o1="$2"
+  echo "$o0" | sed "s/^\s\+//" | sed -E "s/(\w*)_[0-9]*([0-9]{2}),/\L\1\2${o1},/"
+}
+
+function _eq_ {
+  _o="$1"
+  o0=$(echo "$1" | grep -E "(pages|issn)\s*=") # dash between numbers
+  if test -n "$o0" ; then
+    _o=$(echo "$_o" | sed 's/\([0-9]\+\s\?\)[–-]\(\s\?[0-9]\+\)/\1--\2/')
+  fi
+  o0=$(echo "$1" | grep -E "(author|editor)\s*=") # NAME --> Name
+  if test -n "$o0" ; then
+    _o=$(echo "$_o" | sed 's/\([[:upper:]]\{2,\}\)/\L\u\1/g')
+  fi
+  echo "$_o"
+}
+
+doi=$(echo "$doi" | sed 's/https\?:\/\/doi.org\///')
+o=$(curl -sLH "Accept: application/x-bibtex" https://doi.org/$doi)
+
+if test -z "$o" ; then
+  if test -n "$q" ; then echo "curl: returns empty! Check then validity of DOI!" ; fi
+  exit 1
 fi
 
-echo "$o" | sed 's/\s*\(\w\+\)=\({[^\{\}]*}\)/\n  \1 = \2/g' | sed 's/},\? \?}/}\n}\n/'
+_o=$(echo "$o" | grep -i "doi not found")
+if test -n "$_o" ; then
+  if test -n "$q" ; then echo "DOI Not Found, which may be not activated Currently!" ; fi
+  exit 1
+fi
+
+tt=$(_t1 "${o}")
+tt=$(_pure_t1 "$tt")
+
+o=$(_rm_items "$o")
+o=$(_tolines "$o")
+while IFS= read -r i ; do
+  o0=$(echo "$i" | grep "@\w\+")
+  if test -n "$o0" ; then
+    _keys "$i" "$tt"
+  else
+    _eq_ "$i"
+  fi
+done <<< "$o"
+
+#o=$(echo $o | sed -E 's/(\w*)_[0-9]*([0-9]{2}),/\L\1\2'"${tt}"',/' | sed 's/month=\w*,\? \?//g' | sed 's/DOI=/doi=/' | sed 's/\(pages\s\?=\s\?{\s\?[0-9]\+\s\?\)[–-]\(\s\?[0-9]\+\)/\1--\2/')
+#if test -n "$b"; then
+#  for i in $(echo "$b" | tr "," " "); do
+#    o=$(echo "$o" | sed 's/'"$i"'={[^\{\}]*},\? \?//gI')
+#  done
+#fi
+#
+#echo "$o" | sed 's/\s*\(\w\+\)=\({[^\{\}]*}\)/\n  \1 = \2/g' | sed 's/},\? \?}/}\n}\n/'
