some improvements 07sep2021

diff --git a/mysh/rn1 b/mysh/rn1
--- a/mysh/rn1
+++ b/mysh/rn1
@@ -1,129 +1,147 @@
 #!/bin/bash
 #
+bold=$(tput bold)
+normal=$(tput sgr0)
 me=$(basename "$0")
 #ext='*'
 if [ "$(which rn4)" ]; then
- RN4=$(which rn4)
+  RN4=$(which rn4)
 else
- cd "$(dirname "${BASH_SOURCE[0]}")"
- pp=$(pwd)
- cd ~-
- if [ -x "${pp}/rn4" ]; then
-  RN4=${pp}/rn4
- fi
+  cd "$(dirname "${BASH_SOURCE[0]}")"
+  pp=$(pwd)
+  cd ~-
+  if [ -x "${pp}/rn4" ]; then
+    RN4=${pp}/rn4
+  fi
 fi
 if [ -z "${RN4}" ]; then
- echo 'rn4 not found; EXIT!!!'
- exit 1
+  echo 'rn4 not found; EXIT!!!'
+  exit 1
 fi
 
 pwd_=$(pwd)
 #getting arguments now
 while test $# -gt 0; do
- case "$1" in
-  -h|--help)
-   echo "$me - rename"
-   echo " "
-   echo "$me [options] [DIRECTORY]"
-   echo " "
-   echo "options:"
-   echo "-h, --help                show brief help"
-   echo "-x, --ext=EXT             only applied for files with this extention"
-   echo "-p, --prefix=PREFIX       PREFIX_XXXX.EXT; default name of targit directory"
-   echo "-i, --ini=INI             basement for increament; default 0"
-   echo "-v                        verbose mode"
-   exit 0
-   ;;
-  -x|--ext)
-   shift
-   if test $# -gt 0; then
-    ext=$1
-    shift
-   fi
-   ;;
-  --ext*)
-   ext=$(echo $1 | sed -e 's/^[^=]*=//g')
-   shift
-   ;;
-  -p|--prefix)
-   shift
-   if test $# -gt 0; then
-    pre=$1
-    shift
-   fi
-   ;;
-  --prefix*)
-   pre=$(echo $1 | sed -e 's/^[^=]*=//g')
-   shift
-   ;;
-  -i|--ini)
-   shift
-   if test $# -gt 0; then
-    k=$1
-    shift
-   fi
-   ;;
-  --ini*)
-   k=$(echo $1 | sed -e 's/^[^=]*=//g')
-   shift
-   ;;
-  -v)
-   v_='-v'
-   shift
-   ;;
-  *)
-   wkd_=$1
-   shift
-   ;;
- esac
+  case "$1" in
+    -h|--help)
+      echo "${bold}$me - rename files sequentially under a directory${normal}"
+      echo " "
+      echo "${bold}usage:${normal} $me [options] [DIRECTORY]"
+      echo " "
+      echo "options:"
+      echo "-h, --help                show brief help"
+      echo "-x, --ext=EXT             only applied for files with this extention; default all"
+      echo "-p, --prefix=PREFIX       PREFIX_XXXX.EXT; default name of targit directory"
+      echo "-i, --ini=INI             basement for increament; default 0"
+      echo "-s                        simulation mode (not executed)"
+      echo "-v                        verbose mode"
+      exit 0
+      ;;
+    -x|--ext)
+      shift
+      if test $# -gt 0; then
+        ext=$1
+        shift
+      fi
+      ;;
+    --ext*)
+      ext=$(echo $1 | sed -e 's/^[^=]*=//g')
+      shift
+      ;;
+    -p|--prefix)
+      shift
+      if test $# -gt 0; then
+        pre=$1
+        shift
+      fi
+      ;;
+    --prefix*)
+      pre=$(echo $1 | sed -e 's/^[^=]*=//g')
+      shift
+      ;;
+    -i|--ini)
+      shift
+      if test $# -gt 0; then
+        k=$1
+        shift
+      fi
+      ;;
+    --ini*)
+      k=$(echo $1 | sed -e 's/^[^=]*=//g')
+      shift
+      ;;
+    -v)
+      v_='-v'
+      shift
+      ;;
+    -s)
+      s_='-s'
+      shift
+      ;;
+    *)
+      wkd_=$1
+      shift
+      ;;
+  esac
 done
 #getting arguments done
 #if change directory
 if [ "${wkd_}" ]; then
- if [ -d "${wkd_}" ]; then
-  if [ "${v_}" ]; then
-   echo 'cd '"${wkd_}"
+  if [ -d "${wkd_}" ]; then
+    if [ "${v_}" ]; then
+      echo 'cd '"${wkd_}"
+    fi
+    cd "${wkd_}"
+  else
+    echo "'${wkd_}' not a directory; EXIT!!!"
+    exit 1
   fi
-  cd "${wkd_}"
- else
-  echo "'${wkd_}' not a directory; EXIT!!!"
 fi
 #to FILENAME.x.EXT
-if [ "${ext}" ]; then
- "${RN4}" -x "${ext}" ${v_}
-else
- "${RN4}" ${v_}
+if [ -z "${s_}" ]; then
+  if [ "${ext}" ]; then
+    "${RN4}" -x "${ext}" ${v_}
+  else
+    "${RN4}" ${v_}
+  fi
 fi
 #PRE_KKKK
 k=${k:-0}
 pre=${pre:-$(pwd | sed 's/.*\///')}
 #packed as an function
 function do_something_ {
- local IFS=$'\n'
- for i in $(find . -d 1 -type f -name "[^\.\_]*${ext:+".${ext}"}" -exec ls -1tr "{}" +;)
- do 
-  k=$((k+1))
-  kk=$(printf "%4.4d" "$k")
-  i_=$(basename "$i")
-  ext_=$([[ "${i_}" = *.* ]] && echo ".${i_##*.}" || echo '')
-  tmp="${pre}_${kk}${ext_}"
-  if [ -f "${tmp}" ]; then
-   echo 'mv' "'$i'" "'${tmp}'" 'failed! TARGET already exists! SKIP!!!'
-  else
-   if [ "${v_}" ]; then
-    echo 'mv' "'$i'" "'${tmp}'" 
-   fi
-   mv "$i" "${tmp}"
-  fi
- done
+  local IFS=$'\n'
+  for i in $(find . -d 1 -type f -name "[^\.\_]*${ext:+".${ext}"}" -exec ls -1tr "{}" +;)
+  do
+    if [ -f "$i" ]; then
+      k=$((k+1))
+      kk=$(printf "%4.4d" "$k")
+      i_=$(basename "$i")
+      ext_=$([[ "${i_}" = *.* ]] && echo ".${i_##*.}" || echo '')
+      tmp="${pre}_${kk}${ext_}"
+      if [ -f "${tmp}" ]; then
+        echo 'mv' "'$i'" "'${tmp}'" 'failed! TARGET already exists! SKIP!!!'
+      else
+        if [ "${s_}" -o "${v_}" ]; then
+          echo 'mv' "'$i'" "'${tmp}'" 
+        fi
+        if [ -z "${s_}" ]; then
+          mv "$i" "${tmp}"
+        fi
+      fi
+    fi
+  done
 }
 #execute function just defined
+if [ "${s_}" ]; then
+  echo "${bold}in simulation mode; NONE changes on disk!!!${normal}"
+fi
 do_something_
 #to where when you did nothing
 if [ "${wkd_}" ]; then
- if [ "${v_}" ]; then
-  echo 'finished; exit.'
- fi
- cd "${pwd_}"
+  if [ "${s_}" -o "${v_}" ]; then
+    echo 'finished; exit.'
+  fi
+  cd "${pwd_}"
 fi
 #finish
diff --git a/mysh/rn2 b/mysh/rn2
--- a/mysh/rn2
+++ b/mysh/rn2
@@ -1,72 +1,91 @@
 #!/bin/bash
 #
+bold=$(tput bold)
+normal=$(tput sgr0)
 me=$(basename "$0")
 ext='*'
 pwd_=$(pwd)
 while test $# -gt 0; do
- case "$1" in
-  -h|--help)
-   echo "$me - replace STR0 in filenames by STR1 under a directory"
-   echo " "
-   echo "$me [options] STR0 STR1"
-   echo " "
-   echo "options:"
-   echo "-h, --help                show brief help"
-   echo "-p                        specify a path; otherwise applied to current directory!"
-   echo "-v                        verbose mode"
-   exit 0
-   ;;
-  -p)
-   shift
-   if test $# -gt 0; then
-    wkd_=$1
-    shift
-   else
-    echo "no path specified; exit"
-    exit 1
-   fi
-   ;;
-  -v)
-   v_='-v'
-   shift
-   ;;
-  *)
-   if [ "${a0}" ]; then
-    a1=$1
-   else
-    a0=$1
-   fi
-   shift
-   ;;
-  esac
+  case "$1" in
+    -h|--help)
+      echo "${bold}$me - replace STR0 in filenames by STR1 under a directory${normal}"
+      echo " "
+      echo "${bold}usage:${normal} $me [options] STR0 [STR1]"
+      echo " "
+      echo "options:"
+      echo "-h, --help                show brief help"
+      echo "-d                        specify a path; otherwise applied to current directory!"
+      echo "-s                        simulation mode (not executed)"
+      echo "-v                        verbose mode"
+      exit 0
+      ;;
+    -d)
+      shift
+      if test $# -gt 0; then
+        wkd_=$1
+        shift
+      else
+        echo "no path specified; exit"
+        exit 1
+      fi
+      ;;
+    -v)
+      v_='-v'
+      shift
+      ;;
+    -s)
+      s_='-s'
+      shift
+      ;;
+    *)
+      if [ "${a0}" ]; then
+        a1=$1
+      else
+        a0=$1
+      fi
+      shift
+      ;;
+    esac
 done
 
 if [ "${a0}" ]; then
- if [ "${wkd_}" ]; then
-  if [ -d "${wkd_}" ]; then
-   if [ "${v_}" ]; then
-    echo 'cd '"${wkd_}"
-   fi
-   cd "${wkd_}"
-  else
-   echo "'${wkd_}' not a directory; EXIT!!!"
- fi
- for i in *"${a0}"*; do
-  tmp_=$(echo "${a0}" | sed 's/\./\\./g')
-  tmp=$(echo "$i" | sed 's/'"$tmp_"'/'"${a1}"'/')
-  if [ -f "${tmp}" ]; then
-   echo 'mv' "'$i'" "'${tmp}'" 'failed! Target already exists! SKIP!!!'
-  else
-   if [ "${v_}" ]; then
-    echo 'mv' "'$i'" "'${tmp}'"
-   fi
-   mv "$i" "$tmp"
+  if [ "${wkd_}" ]; then
+    if [ -d "${wkd_}" ]; then
+      if [ "${v_}" ]; then
+        echo 'cd '"${wkd_}"
+      fi
+      cd "${wkd_}"
+    else
+      echo "'${wkd_}' not a directory; EXIT!!!"
+      exit 1
+    fi
   fi
- done
- if [ "${wkd_}" ]; then
-  cd "${pwd_}"
- fi
+  if [ "${s_}" ]; then
+    echo "${bold}in simulation mode; NONE changes on disk!!!${normal}"
+  fi
+  for i in *"${a0}"*; do
+    if [ -f "$i" ]; then
+      tmp_=$(echo "${a0}" | sed 's/\./\\./g')
+      tmp=$(echo "$i" | sed 's/'"$tmp_"'/'"${a1}"'/')
+      if [ -f "${tmp}" ]; then
+        echo 'mv' "'$i'" "'${tmp}'" 'failed! Target already exists! SKIP!!!'
+      else
+        if [ "${s_}" -o "${v_}" ]; then
+          echo 'mv' "'$i'" "'${tmp}'"
+        fi
+        if [ -z "${s_}" ]; then
+          mv "$i" "$tmp"
+        fi
+      fi
+    fi
+  done
+  if [ "${wkd_}" ]; then
+    if [ "${s_}" -o "${v_}" ]; then
+      echo 'finished; exit.'
+    fi
+    cd "${pwd_}"
+  fi
 else
- echo "STR0 not specified; exit"
- exit 1
+  echo "STR0 not specified; EXIT!!!"
+  exit 1
 fi
